setThemeMode(themeStatus)
themeBtnElem.addEventListener("click", themeBtnClickHandler)
menuBtnElem.addEventListener("click", menuBtnClickHandler)
window.addEventListener("resize", windowResizeHandler)
window.addEventListener("load", windowLoadHandler)
volumeBtnElem.addEventListener("click", volumeBtnClickHandler)
nextBtnElem.addEventListener("click", nextBtnClickHandler)
playStopBtnElem.addEventListener("click", playStopBtnClickHandler)
previousBtnElem.addEventListener("click", previousBtnClickHandler)
repeatBtnElem.addEventListener("click", repeatBtnClickHandler)
searchBoxElem.addEventListener("keyup", searchBoxKeyUpHandler)